name = "my-worker"
compatibility_date = "2024-03-15"

account_id = "e6aba92e9aa0421804f64f17b0e07e26"  # Ensure this matches your Cloudflare account ID

[[d1_databases]]
binding = "DB"
database_name = "retreat_db"
database_id = "4df92c4c-118f-41d9-8359-b474922ec06d"
